# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

on:
  workflow_dispatch:

jobs:
  build:
    name: Build charm
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic

      - name: Pack charm
        run: charmcraft pack -v

      - name: conceirge
        run: sudo snap install --classic concierge && sudo concierge prepare -p dev

      - name: tox -e integration
        run: tox -e integration

